
title: Homepage of Semoo Shin
url: 'https://0llan.github.io/'
baseurl: '0llan.github.io'

# Profile information
yourname: Semoo Shin
title: 'HCIS Lab, GIST'  ## your title
location: Gwangju, Republic of Korea

## Social Profiles
linkedin: https://www.linkedin.com/in/semoo-shin-161811263/
google: https://scholar.google.com/citations?user=w5b-UFcAAAAJ
orcid: https://orcid.org/0009-0001-0092-1948

# Update all the sections by editing the files inside _includes folder.
